### ISSUE TITLE
Dashboard is a thing now!

### ISSUE THREAD

**Issue by jsleslie** [UBC-MDS/DSCI532_Group215_ParticulatesMatter#16]
Hey guys, I'm getting ready to put through a pull request of our app.py.

Here's how it looks on my browser: 
![image](https://user-images.githubusercontent.com/31370668/69704551-7f07f700-10a8-11ea-9a30-576967ae0db6.png)

One difference is the date control slider takes up the full bottom. This was something Firas suggested we do since everything else in the slide bar would control only a single graphic. Thoughts?

**Comment by KarlosMuradyan** [comment]
This looks amazing!! But the colors make the dashboard a little bit childish)) I think if we can come up with other idea of visually separating the charts other than colors, it will be more pleasant for eyes.

**Comment by tejasph** [comment]
I agree with Karlos on this. We can decide together which colors look the best.
