### ISSUE TITLE
Reviewing Section 2 of the Dashboard proposal.md

### ISSUE THREAD

**Issue by tejasph** [UBC-MDS/DSCI532_Group215_ParticulatesMatter#8]
Just a few comments about Section 2:

1. Might want to define the difference between RAW_VALUE and ROUNDED_VALUE for clarity reasons.

2. Clarify what is meant by locations?  Are there multiple locations in a single city or is it just one location per city for the pollutant readings?

3. One of the expectations in our milestone is "Point form may occur, but should be less than 10% of your written documents." We should probably change the formatting to be in paragraph form.

**Comment by KarlosMuradyan** [comment]
@jsleslie, could you please also write 1/2 sentences about data wrangling done? For example, in your lab4 you mentioned that there are 9 PMs, but you chose only 2 of them.

**Comment by jsleslie** [comment]
Addressed in latest pull request
